### ISSUE TITLE
images.immatch missing?

### ISSUE THREAD

**Issue by dancoe** [spacetelescope/stak-notebooks#103]
Searching this documentation, I can't seem to find the old IRAF images.immatch functions:
http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?immatch.hlp

I did eventually find that one of the functions "wregister" is now called "reproject":
https://reproject.readthedocs.io/en/stable/

This is my first time here on STAK and my first issue submission, so my apologies if I just missed this somewhere.  Thank you for all your work on this project!

**Comment by SaOgaz** [comment]
Hey @dancoe, thanks for posting this as an issue!  I was not able to add a notebook for that module, partially because a significant amount of the WCS stuff is still under development in Astropy.  I will definitely consider this as a request for that notebook in particular if we are able to add more.  I will add this as a new issue for clarity.

**Comment by SaOgaz** [comment]
@dancoe you good with me closing this?
