### ISSUE TITLE
INS Review: lists

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#56]

**Comment by sean-lockwood** [comment]
Typo:  `new xyvalues` --> `new yvalues`

**Comment by samanthalh** [comment]
In the description cell of the lintran example, fix typo "transfrom" to "transform" in sentence below.

The lintran task will linear transfrom a list of coordinates.

**Comment by samanthalh** [comment]
In the description cell of the lintran example, add "be" between "can used" to the sentence below so that it makes grammatical sense. 

Current: There are various tasks in the numpy linear algebra package that can used to achieve this in Python.
Change: There are various tasks in the numpy linear algebra package that can be used to achieve this in Python.

**Comment by samanthalh** [comment]
In the lintran example, add a second example that directly relates to an astronomy problem for which lintran would have been used. Google tells me one idea is shifting photometry coordinates between offset images. So, take a short list of X and Y pixel values, and shift them X+10 and Y+23, or whatever. This is actually mathematically easier than the current example, but will show how the code might be used the way lintran previously was in IRAF. 

Edit: Sara, I just read this and realized it sounded very simple. Show them how to add?? But I think the virtue of lintran is that it read and output types of files while keeping the formatting standard, and this is what they're going to be upset about losing. Reading in a DAOPHOT file (to pick one I'm familiar with), shifting the coordinates as above, and then outputting it so that it's still formatted to be parsed by DAOPHOT is a common task. Do we have an example that teaches reading and writing files with particular formatting? Maybe link to that section, or create that example here.

**Comment by jaymedina** [comment]
## table-unique
Possible typo: 'The table task **task** a list of text...'

**Comment by SaOgaz** [comment]
Hey @samanthalh, I think in this situation I'm going to assume users are doing their "due diligence" and will read through some basic array documentation to find out how to do more simple things.  I realize this isn't always the reality, but I don't want this resource to become a "here's how you use basic Python" kind of guide.

To address the DAOPhot example specifically, I think this is something I will keep in mind as DATB continues to work on the photutils package and it's documentation.

**Comment by SaOgaz** [comment]
I've incorporated all fixes up to here.

**Comment by SaOgaz** [comment]
Exchange the raverage example for a more simple one, but still link to the more complicated example.
