### ISSUE TITLE
INS Review: noao.imred.crutil

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#58]

**Comment by samanthalh** [comment]
The functions cosmicrays, craverage, crfix are still empty.

**Comment by SMBaggett** [comment]
**crgrow**

- Typos in imred Intro:  algorithims, comsic rays
- Note: test_data did not include the blv_tmp.fits shown in example.
- Typo in code section: bytesway  should be byteswap
- Could this comment be expanded upon: 

```
# Read in your fits file, when using a fits file, the bytesway call is required to
# make sure your array data type is correct.

What is the issue? Superficially the results look identical regardless of byteswap use:

In [91]: dq1noswap = hdu[3].data
In [92]: help,dq1noswap
Out[92]:
(Type help() for interactive help, or help(object) for help about object.,
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [528, 528, 512, ..., 512, 512, 528],
        [528, 528, 528, ..., 512, 512, 512]], dtype=int16))

In [93]: help,dq1
Out[93]:
(Type help() for interactive help, or help(object) for help about object.,
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [528, 528, 512, ..., 512, 512, 528],
        [528, 528, 528, ..., 512, 512, 512]], dtype=int16))

In [94]: dq1-dq1noswap
Out[94]:
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)


```
- Need some more detail on options for the 2nd parameter fed to 'dilation' and what they produce. The 'disk(2)' for example, doesn't seem to flag in circular disk shape but rather a large oval. The disk(1) flags in "+" shape which is equivalent to the pyraf crgrow radius=1 setting. E.g.
```

In [143]: inarr
Out[143]:
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
In [146]: outarr = dilation(inarr, disk(1))
In [147]: outarr
Out[147]:
array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.]])
In [149]: outarr = dilation(inarr, disk(2))
In [150]: outarr
Out[150]:
array([[0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.]])
```

- Would highlight the need to import the "shape" in the skimage call at top. That is, in example it was disk; to flag pixels all around a value requires shape of 'square'

- Would show simplistic case using arrays, something like

```
In [137]: inarr = np.arange(25).reshape(5,5)*0.
In [138]: inarr[2,2] = 1

In [139]: inarr
Out[139]:
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

And showcase that 'square' will flag entire perimeter of pixels around target
 (while disk(1) does a '+')
In [140]: outarr = dilation(inarr, square(3))
In [141]: outarr
Out[141]:
array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])
```

- NOTE: '+' correction in python does NOT produce same results as in iraf crgrow. Will require more testing to determine the cause of the discrepancy.

```

In [154]: inimage = 'test_data/ido995fhq_flt.fits'
In [155]: hdu = fits.open(inimage,mode='update')
In [156]: dq1 = hdu[3].data.byteswap().newbyteorder('=')
In [157]: grownDQ = dilation(dq1,disk(1))
In [158]: hdu[3].data = grownDQ
In [159]: hdu.close()

crgrow ido995fhq_flt.fits[3] ido995fhq_iraf.fits radius=1. inval=INDEF outval=INDEF

#                    IMAGE      NPIX      MEAN    STDDEV       MIN       MAX     MIDPT
safe.ido995fhq_flt.fits[3]    710649     4579.     3935.        4.     9232.     7902.
    ido995fhq_iraf.fits[3]   3744180     3031.     3817.        4.     9232.     384.3
     ido995fhq_flt.fits[3]   2066715     3640.     3933.        4.     9232.     983.6

```

**Comment by SMBaggett** [comment]
**crmedian**

- imred.crutil typo ... algorithim   comsic

- There's a note at bottom of crutil page re: crcombine as "work in progress" -- perhaps don't bother to replace that one?
- crmedian intro typos ... indentify  indentfied  algorithim
- Example needs more detail, including how to convert newdata back into fits image so that results can be compared to idl/iraf output
- First time through, it could not find ccdproc

```
In [58]: from ccdproc import cosmicray_median, fits_ccddata_reader
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-58-97b3b50bff4c> in <module>()
----> 1 from ccdproc import cosmicray_median, fits_ccddata_reader

ModuleNotFoundError: No module named 'ccdproc'

```
JMed suggested pip install which fixed it; would add this tip to crmedian Intro
(stak_env) sekhmet:test_data sbaggett$ pip install ccdproc
Collecting ccdproc
[ many output message, removed to declutter]

**Comment by SMBaggett** [comment]
**crnebula**

- Section of this in current notebook is empty. Perhaps a Jupyter version isn't even needed, is there mechanism to poll potential past users to confirm that it's not widely used (I've never used it myself)

**Comment by SaOgaz** [comment]
@SMBaggett, the differences from byteswap happens after dilation is run.  I vaguely remember tracking down why this was happening, but no longer remember the specifics. It's something about the way dilation is implemented and the integer type.

```
# Change this value to your desired data file
test_data = '/eng/ssb/iraf_transition/test_data/iczgs3ygq_flt.fits'
out_file = 'crgrow.fits'
​
# Read in your fits file, when using a fits file, the byteswap call is required to
# make sure your arry data type is correct.
hdu = fits.open(test_data,mode='update')
dq1 = hdu[3].data.byteswap().newbyteorder('=')
​
# Dilation used to grow the CR flags
grownDQ = dilation(dq1, disk(2))
​
print(grownDQ)
​
# Re-assign the changed array to our original fits file and close save the updated FITS to a new file.
hdu[3].data = grownDQ
hdu.writeto(out_file, overwrite=True)
[[  0   0   0 ...,  44  44  44]
 [  0   0   0 ...,  44  44  44]
 [  0   0   0 ...,  44  44  44]
 ..., 
 [ 44 300 300 ...,  44  44  44]
 [ 44  44 300 ...,  44  44  44]
 [ 44  44  44 ...,  44  44  44]]

# Change this value to your desired data file
test_data = '/eng/ssb/iraf_transition/test_data/iczgs3ygq_flt.fits'
out_file = 'crgrow.fits'
​
# Read in your fits file, when using a fits file, the byteswap call is required to
# make sure your arry data type is correct.
hdu = fits.open(test_data,mode='update')
dq1 = hdu[3].data#.byteswap().newbyteorder('=')
​
# Dilation used to grow the CR flags
grownDQ = dilation(dq1, disk(2))
​
print(grownDQ)
​
# Re-assign the changed array to our original fits file and close save the updated FITS to a new file.
hdu[3].data = grownDQ
hdu.writeto(out_file, overwrite=True)
[[    0     0     0 ..., 11264 11264 11264]
 [    0     0     0 ..., 11264 11264 11264]
 [    0     0     0 ..., 11264 11264 11264]
 ..., 
 [11264 11265 11265 ..., 11264 11264 11264]
 [11264 11264 11265 ..., 11264 11264 11264]
 [11264 11264 11264 ..., 11264 11264 11264]]
```

**Comment by philhodge** [comment]
I don't think you should need to call byteswap.  I don't use it.

**Comment by SaOgaz** [comment]
@philhodge, is there another work around? If I don't use that dilation gives me weird results.

**Comment by SaOgaz** [comment]
I've incorporated all comments up to here.

**Comment by philhodge** [comment]
Regarding the need for swapping bytes after running `dilation`, I think that's a bug in `dilation`, or at least incomplete documentation.  The help for `skimage.morphology.dilation` does use `uint8` (and it refers to `uint16`) in the description and example, but it doesn't say that you can't use `int16`.  When I ran a quick test (running on a Linux machine) using `int16` data that I had written to and then read back from a FITS file, the output of `dilation` was byte swapped:

y = fits.getdata("arange.fits")
y.dtype
dtype('>i2')                               # note '>i2' rather than 'int16'
print(y)
[[  0   1   2   3   4   5   6]
 [  7   8   9  10  11  12  13]
 [ 14  15  16 100  18  19  20]
 [ 21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34]]
z = morphology.dilation(y, out=None)
z.dtype
dtype('>i2')
print(z)
[[ 1792  2048  2304  2560  2816  3072  3328]
 [ 3584  3840  4096 25600  4608  4864  5120]
 [ 5376  5632 25600 25600 25600  6656  6912]
 [ 7168  7424  7680 25600  8192  8448  8704]
 [ 7424  7680  7936  8192  8448  8704  8704]]
zb = z.byteswap()
print(zb)
[[  7   8   9  10  11  12  13]
 [ 14  15  16 100  18  19  20]
 [ 21  22 100 100 100  26  27]
 [ 28  29  30 100  32  33  34]
 [ 29  30  31  32  33  34  34]]

On Linux, the native byte order is not the same as in a FITS file, but numpy handles this transparently.  My guess is that `dilation` is written in C, and something with regard to the data type was overlooked.  When I tried the above using an array starting with data type `np.uint16` (then written to and read back from a FITS file), `dilation` worked OK.  (I didn't actually need to write the array to a FITS file and then read it back in; I could have created the array with dtype '>i2' in the first place.)  So that might be a useful workaround:  use `uint16` instead of `int16`.

That said, I'm not convinced that `dilation` actually does anything useful with regard to cosmic rays.  The CR tasks for HST instruments have an option to search the neighborhood of a CR with a reduced threshold, which can expand the flagging around a CR hit, but only to pixels that actually have higher than expected counts.

**Comment by SaOgaz** [comment]
@philhodge, I know that wfc3 at least uses the dilation on DQs for some of their references files.  Thanks for the research, I'll see if I can change out my example.
