### ISSUE TITLE
INS Review: stsdas.toolbox.imgtools.mstools

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#63]

**Comment by SaOgaz** [comment]
From meeting with Sylvia:

add second example to msstat, use iczgs3y5q_flt.fits file, loop through SCI extensions, move bitmap masking to this second example.

**Comment by SMBaggett** [comment]
@SaraOgaz  Thanks for capturing that. Meanwhile I've tried to work through the python msstat example but there are aspects about it that it seems I've misunderstood even after reading the help on bitfield_to_boolean_mask helpfile

- notebook example works fine, typing in the commands reproduces mean,median,std in notebook but it's unclear how "bits 32 and 4" in the comment map to the "~4, 128" in the bitfield call.
```

WFC3 data only have 16 bits available where
bit 4 has flag of 8 in DQ             i.e. 0000 0000 0000 1000
bit 8 has flag value of 128           i.e. 0000 0000 1000 0000

```

- Trying to flag all values in DQ (where original DQ values set to "2" if greater than 0) does not work:
```

-> imreplace iczgs3y5q_ima.fits[3] 2. low=0.5
               IMAGE      NPIX      MEAN    STDDEV       MIN       MAX     MIDPT
 iczgs3y5q_ima.fits[3]   1001184        0.        0.        0.        0.     INDEF    upp=0.5
 iczgs3y5q_ima.fits[3]     47392        2.        0.        2.        2.     INDEF    low=0.5

from astropy.io import fits
from astropy import stats
from stsci.tools.bitmask import bitfield_to_boolean_mask
indata = 'iczgs3y5q_ima.fits'
hdulist = fits.open(indata)
boolean_mask = bitfield_to_boolean_mask(hdulist[3].data,"2")
mean,median,std = stats.sigma_clipped_stats(hdulist[1].data,mask=boolean_mask,sigma=0.0,iters=0)
mean,std,median

In [8]: mean,std,median
Out[8]: (masked, masked, 0.0)

Tried it without the "2", now there are numbers but mean, std are incorrect (midpt is at least close):
boolean_mask = bitfield_to_boolean_mask(hdulist[3].data)
mean,median,std = stats.sigma_clipped_stats(hdulist[1].data,mask=boolean_mask,sigma=0.0,iters=0)

In [12]: mean,std,median
Out[12]: (1.610540314029794, 16.40580198316299, 0.7965517044067383)

From pyraf msstat:
msstat iczgs3y5q_ima.fits stats=npix,mean,stddev,min,max,midpt >& pyraf_msstat.out
# image                         npix        mean      stddev         min         max       midpt
#
iczgs3y5q_ima.fits[SCI,1]   1001184.    0.789796     1.42296    -121.463     111.757    0.783849 
...

```

Note that my examples were attempting to avoid sigma-clipping in order to retrieve statistics based on all the unflagged pixels; could that be contributing to the problem?

- What does the 'bitflip' (~) do?

**Comment by tddesjardins** [comment]
Echoing @SMBaggett's comment, I'm a little confused by the ignore_bits setting here. From what I can tell from the documentation, your use of "~4, 128" should mean that only pixels with DQ flags 4 and 128 are being included in the statistical calculations while everything else is being masked. I double checked and the number pixels with in iczgs3ygq_flt.fits[3] with DQ flag 0 is 990,475, but the boolean mask only has 3,358 good values. If you meant to exclude everything except 4 and 32, I'd make this a bit more clear in the comment. Also either fix the comment or the code so that they use the same DQ flags (either 4 and 32 or 4 and 128).

**Comment by SaOgaz** [comment]
You're right @tddesjardins, I forgot to reverse my output.  @SMBaggett, sorry for the mis-leading example.  The reason we have to do a "flip" and then another "flip" is because of DQ values that contain the flag you don't want to use, and another acceptable flag. For example, if we were trying to use "4", and looking at a value of 6 in the actual DQ array (4+2), the bitfield to boolean function would still accept that value as "don't mask" because it has a flag we want (2).  By telling bitfield to boolean to consider the provided values (4) as the flags we want (not the flags to ignore), it will take any "4"s AND any values that contain "4".  But then the output mask is the opposite of the boolean output we want.  So we have to reverse it yet again.  Does this make sense? I'll try and add a better explanation to the notebook.

**Comment by tddesjardins** [comment]
I would suggest keeping the way you're trying to do it, but maybe also presenting a different way. Whenever I do this kind of masking, I use the `numpy.bitwise_and()` function. So, if I wanted to mask all pixels that have, for example, bit flag 4 contained in the sum of all flags for that pixel, I would do:

```
mask = numpy.zeros(hdulist[3].data.shape[0], hdulist[3].data.shape[1]).astype(bool)
bad_dq_4 = numpy.bitwise_and(hdulist[3].data, 4).astype(bool)
mask += bad_dq_4
```

If I want to add another DQ flag to it (e.g., 32), I can just:

```
bad_dq_32 = numpy.bitwise_and(hdulist[3].data, 32).astype(bool)
mask += bad_dq_32
```

These masks now contain all pixels that are not only equal to 4 and 32 (or 36 in the current example), but all pixels that contain them such as 132 or 164 (4+128 and 4+32+128, respectively). The `astype(bool)` statements are not strictly necessary until you want to finalize the mask if you want to see more information about the pixels you're masking, but I've thrown them in there for this example. The initial `numpy.zeros()` call to make the mask isn't really necessary either, but instructional for novice users.

**Comment by SaOgaz** [comment]
For posterity, this conversation has convinced me that using our stsci.tools version is not worth the possible confusion to users.  Taking Tyler's suggestion even further and just having a native Python bitmask, which can be done in one line.

**Comment by SaOgaz** [comment]
All comments include up to here.
