### ISSUE TITLE
INS Review: tables.fitsio

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak-notebooks#65]

**Comment by sean-lockwood** [comment]
**`stwfits`**
On my system:
```
In [35]: f = readgeis.readgeis('/eng/ssb/iraf_transition/test_data/x31g0108t.c0h')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-d11c552bef18> in <module>()
----> 1 f = readgeis.readgeis('/eng/ssb/iraf_transition/test_data/x31g0108t.c0h')

/Users/lockwood/anaconda3/envs/iraf27/lib/python2.7/site-packages/stsci.tools-3.4.11-py2.7.egg/stsci/tools/readgeis.pyc in readgeis(input)
    203     _shape = _naxis[1:]
    204     _shape.reverse()
--> 205     _code = fits.hdu.ImageHDU.NumCode[_bitpix]
    206     _bscale = phdr.get('BSCALE', 1)
    207     _bzero = phdr.get('BZERO', 0)

AttributeError: type object 'ImageHDU' has no attribute 'NumCode'
```

There may be an incompatibility between `stsci.tools.readgeis` and modern `astropy.io.fits`.

**Comment by SaOgaz** [comment]
I think stsci.tools has a couple compatibility issues, I need to follow up on this, thanks @sean-lockwood!

**Comment by SMBaggett** [comment]
**catfits** 

- General info - would include meaning of those acronyms for folks -- FITS (flexible image transport system) and GEIS (generic edited information set, in use for many years before FITS)

- The catfits routine is still very useful so thank you for providing a means to do it.

- Would also provide an extremely simple example (in ipython, it's only 3 lines) :
```

from astropy.io import fits
image = 'ido995fhq_flt.fits'
fits.info(image)

In [21]: fits.info(image)
Filename: ido995fhq_flt.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     272   ()      
  1  SCI           1 ImageHDU        90   (4096, 2051)   float32   
  2  ERR           1 ImageHDU        43   (4096, 2051)   float32   
  3  DQ            1 ImageHDU        35   (4096, 2051)   int16   
  4  SCI           2 ImageHDU        90   (4096, 2051)   float32   
  5  ERR           2 ImageHDU        43   (4096, 2051)   float32   
  6  DQ            2 ImageHDU        35   (4096, 2051)   int16   

In [22]: 

```

**Comment by SaOgaz** [comment]
@sean-lockwood, looks like they fixed it in version 3.4.12 of stsci.tools.  Want to update your package and see if it works for you now?

**Comment by rayalucas** [comment]
# stwfits
Before attempting to run the stak Jupyter notebook on 09 March, 2018, I started a new bash session (command was bash -l), successfully updated my Conda installation with the usual commands ("source activate astroconda", followed by "conda update --all"), and then tried to run the notebooks. I got the errors as shown below in "before" and "after" views (I added the notebook steps "In [1]:" etc. manually afterwards to this note for readability, to reflect what the screen actually said, as well.)  There were warnings about possible BYTESWAP issues. Perhaps the problem was that the image in question may have been written on a linux machine and I was trying to run it on a Mac? (I'm don't recall for sure at the moment if those two are BYTE-swapped.) It suggests that one may want to apply the '.byteswap()' method, but I would suggest that for convenience of the user, it is perhaps better to have that as a preliminary question and an intermediate step in the Jupyter notebook example, saying which kind of BYTE arrangement the image is in, and then having the user run that step first , as needed, if it is in the wrong BYTE order for the user's machine. That way, the user will also immediately see how to do byte-swapping of images, if that is indeed the issue. I'm not absolutely sure that was the reason for the error here, though, as there seemed to be a permissions error with changing/re-writing/overwriting the CD matrix in the header.

BEFORE:
----------- 

In [3]:
from stsci.tools import readgeis

In [4]:
filename = '/eng/ssb/iraf_transition/test_data/x31g0108t.c0h'
hdulist = readgeis.readgeis(filename)
hdulist[1].data = hdulist[1].data.byteswap()
del hdulist[1].header['CD1_1']
del hdulist[1].header['CD2_2']
hdulist.writeto(filename.replace('.c0h','.fits'), clobber=True)
===================================
= WARNING:                        =
=  Input image:                   =
/eng/ssb/iraf_transition/test_data/x31g0108t.c0h[1]
=  had floating point data values =
=  of NaN and/or Inf.             =
===================================
===================================
=  This file may have been        =
=  written out on a platform      =
=  with a different byte-order.   =
=                                 =
=  Please verify that the values  =
=  are correct or apply the       =
=  '.byteswap()' method.          =
===================================

WARNING: AstropyDeprecationWarning: The NumCode class attribute is deprecated and may be removed in a future version.
        Use the module level constant BITPIX2DTYPE instead. [astropy.utils.decorators]
/Users/ogaz/miniconda2/envs/irafdev/lib/python2.7/site-packages/stsci.tools-3.4.11-py2.7.egg/stsci/tools/readgeis.py:250: RuntimeWarning: invalid value encountered in isnan
  (numpy.any(numpy.isnan(ext_dat)) or numpy.any(numpy.isinf(ext_dat))):


AFTER (had an error, and note that I had started over just before this, getting back into bash, updating Conda, etc., then loading notebook, and trying to run):
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [1]:
from stsci.tools import readgeis

In [2]:
filename = '/eng/ssb/iraf_transition/test_data/x31g0108t.c0h'
hdulist = readgeis.readgeis(filename)
hdulist[1].data = hdulist[1].data.byteswap()
del hdulist[1].header['CD1_1']
del hdulist[1].header['CD2_2']
hdulist.writeto(filename.replace('.c0h','.fits'), clobber=True)
===================================
= WARNING:                        =
=  Input image:                   =
/eng/ssb/iraf_transition/test_data/x31g0108t.c0h[1]
=  had floating point data values =
=  of NaN and/or Inf.             =
===================================
===================================
=  This file may have been        =
=  written out on a platform      =
=  with a different byte-order.   =
=                                 =
=  Please verify that the values  =
=  are correct or apply the       =
=  '.byteswap()' method.          =
===================================

WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [__main__]
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-2-e01c3412a9b3> in <module>()
      4 del hdulist[1].header['CD1_1']
      5 del hdulist[1].header['CD2_2']
----> 6 hdulist.writeto(filename.replace('.c0h','.fits'), clobber=True)

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py in writeto(self, fileobj, output_verify, overwrite, checksum)
    876         # file object that's open to write only, or in append/update modes
    877         # but only if the file doesn't exist.
--> 878         fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
    879         hdulist = self.fromfile(fileobj)
    880         try:

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    505                         # one with the name of the new argument to the function
    506                         kwargs[new_name[i]] = value
--> 507             return function(*args, **kwargs)
    508 
    509         return wrapper

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/io/fits/file.py in __init__(self, fileobj, mode, memmap, overwrite, cache)
    148             self._open_fileobj(fileobj, mode, overwrite)
    149         elif isinstance(fileobj, string_types):
--> 150             self._open_filename(fileobj, mode, overwrite)
    151         else:
    152             self._open_filelike(fileobj, mode, overwrite)

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/io/fits/file.py in _open_filename(self, filename, mode, overwrite)
    478 
    479         if mode == 'ostream':
--> 480             self._overwrite_existing(overwrite, None, True)
    481 
    482         if os.path.exists(self.name):

~/anaconda3/envs/astroconda/lib/python3.5/site-packages/astropy/io/fits/file.py in _overwrite_existing(self, overwrite, fileobj, closed)
    397                     if not closed:
    398                         fileobj.close()
--> 399                     os.remove(self.name)
    400             else:
    401                 raise IOError("File {!r} already exists.".format(self.name))

PermissionError: [Errno 13] Permission denied: '/eng/ssb/iraf_transition/test_data/x31g0108t.fits'

**Comment by tddesjardins** [comment]
This function works fine for me as-is. I would maybe say something in the notes that if the image looks like junk then it needed to by byteswapped for sure.

**Comment by sean-lockwood** [comment]
@SaraOgaz  @tddesjardins :  The upgrade of `stsci.tools` from 3.4.11 to 3.4.12 fixed the issue.

**Comment by SaOgaz** [comment]
Incorporated all comments up to her.
